export const DECORATORS_PREFIX = 'asyncapi';
export const METADATA_FACTORY_NAME = '_ASYNCAPI_METADATA_FACTORY';
export const DECORATORS = {
  MESSAGE: `${DECORATORS_PREFIX}/message`,
  CONSUMER: `${DECORATORS_PREFIX}/consumer`,
  PUBLISHER: `${DECORATORS_PREFIX}/publisher`,
  API_MODEL_PROPERTIES: `${DECORATORS_PREFIX}/modelProperties`,
  API_MODEL_PROPERTIES_ARRAY: `${DECORATORS_PREFIX}/modelPropertiesArray`,
};
