export const DECORATORS_PREFIX = 'asyncapi';
export const DECORATORS = {
  ASYNCAPI_SERVICE: `${DECORATORS_PREFIX}/service`,
  ASYNCAPI_PUB: `${DECORATORS_PREFIX}/pub`,
  ASYNCAPI_SUB: `${DECORATORS_PREFIX}/sub`,
};
